### PR TITLE
Add Socks Proxy(Created by MrSonicMaster)

### PR DESCRIPTION
**Pull request by yario-o**
Credits to MrSonicMaster

### CODE REVIEW

**Comment by dahquan** [comment]
You are editing the dist bot.js, you should be editing the src

**Comment by sandor111** [comment]
Close this pulk request please.

**Comment by yario-o** [comment]
@dahquan but it work for me?

**Comment by yario-o** [comment]
on feedme.js there is const Bot = require('../dist')

**Comment by dahquan** [comment]
Yes, but the dist folder is what's generated from the src folder. It will work, but it will also be overwritten when any new changes are made.

**Comment by yario-o** [comment]
Okay

**Pull request closed without merging**
